const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.TiledBg,
		C3.Plugins.Sprite,
		C3.Plugins.Mouse,
		C3.Plugins.Keyboard,
		C3.Behaviors.Anchor,
		C3.Behaviors.Pin,
		C3.Behaviors.Flash,
		C3.Behaviors.Platform,
		C3.Behaviors.bound,
		C3.Plugins.Touch,
		C3.Plugins.Audio,
		C3.Behaviors.solid,
		C3.Behaviors.Sin,
		C3.Plugins.Button,
		C3.Behaviors.scrollto,
		C3.Plugins.Text,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Acts.ResetGlobals,
		C3.Behaviors.Pin.Acts.PinByProperties,
		C3.Plugins.Audio.Acts.Play,
		C3.Behaviors.Platform.Acts.SimulateControl,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Plugins.Keyboard.Cnds.OnKeyReleased,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Text.Acts.SetText,
		C3.Behaviors.Platform.Cnds.IsFalling,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Acts.RestartLayout,
		C3.ScriptsInEvents["FolhaDeEventosFase0.2_Event9_Act5"],
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Behaviors.Platform.Cnds.IsMoving,
		C3.ScriptsInEvents["FolhaDeEventosFase0.2_Event15_Act1"],
		C3.ScriptsInEvents["FolhaDeEventosFase0.2_Event16_Act1"],
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.System.Cnds.Else,
		C3.ScriptsInEvents["FolhaDeEventosFase0.1_Event7_Act1"],
		C3.ScriptsInEvents["FolhaDeEventosFase0.1_Event8_Act3"],
		C3.ScriptsInEvents.FolhaDeEventosFinal_Event5_Act1
	];
};
self.C3_JsPropNameTable = [
	{PlanodefundoTelainicial: 0},
	{Botão: 0},
	{Mouse: 0},
	{Teclado: 0},
	{Âncora: 0},
	{planodefuntoFase2: 0},
	{Fixar: 0},
	{ElaraFase1: 0},
	{direcao: 0},
	{Piscar: 0},
	{Plataforma: 0},
	{RestritoAoLayout: 0},
	{Minotauro: 0},
	{Toque: 0},
	{Áudio: 0},
	{Sólido: 0},
	{espinho: 0},
	{ChãoFase2: 0},
	{ChãoFase02: 0},
	{PlataformaFase1: 0},
	{Senóide: 0},
	{Monstrinho: 0},
	{planodefundoHistória: 0},
	{Botão2: 0},
	{BotãoJogar: 0},
	{CentrarEm: 0},
	{ElaraFase2: 0},
	{vidas: 0},
	{Texto2: 0},
	{vidas2: 0},
	{Texto: 0},
	{portal2: 0},
	{planodefundoFinal: 0},
	{àrvoreDaVida: 0},
	{PlanodefundoFase1: 0},
	{PedraDeLuz: 0},
	{Portal: 0},
	{Planodefundogamerover: 0},
	{Reiniciar: 0},
	{História: 0},
	{Texto3: 0},
	{marcador: 0},
	{colisão: 0},
	{ElaraF: 0},
	{Chão: 0},
	{JogarN: 0},
	{Texto4: 0},
	{marcador2: 0},
	{Parabens: 0},
	{planodefundogameover2: 0},
	{Reiniciar2: 0},
	{chãoFase1: 0},
	{Vidas1: 0}
];

self.InstanceType = {
	PlanodefundoTelainicial: class extends self.ITiledBackgroundInstance {},
	Botão: class extends self.ISpriteInstance {},
	Mouse: class extends self.IInstance {},
	Teclado: class extends self.IInstance {},
	planodefuntoFase2: class extends self.ITiledBackgroundInstance {},
	ElaraFase1: class extends self.ISpriteInstance {},
	Minotauro: class extends self.ISpriteInstance {},
	Toque: class extends self.IInstance {},
	Áudio: class extends self.IInstance {},
	espinho: class extends self.ISpriteInstance {},
	ChãoFase2: class extends self.ISpriteInstance {},
	ChãoFase02: class extends self.ISpriteInstance {},
	PlataformaFase1: class extends self.ISpriteInstance {},
	Monstrinho: class extends self.ISpriteInstance {},
	planodefundoHistória: class extends self.ITiledBackgroundInstance {},
	Botão2: class extends self.IButtonInstance {},
	BotãoJogar: class extends self.ISpriteInstance {},
	ElaraFase2: class extends self.ISpriteInstance {},
	vidas: class extends self.ISpriteInstance {},
	Texto2: class extends self.ITextInstance {},
	vidas2: class extends self.ISpriteInstance {},
	Texto: class extends self.ITextInstance {},
	portal2: class extends self.ISpriteInstance {},
	planodefundoFinal: class extends self.ITiledBackgroundInstance {},
	àrvoreDaVida: class extends self.ISpriteInstance {},
	PlanodefundoFase1: class extends self.ITiledBackgroundInstance {},
	PedraDeLuz: class extends self.ISpriteInstance {},
	Portal: class extends self.ISpriteInstance {},
	Planodefundogamerover: class extends self.ITiledBackgroundInstance {},
	Reiniciar: class extends self.ISpriteInstance {},
	História: class extends self.ITiledBackgroundInstance {},
	Texto3: class extends self.ITextInstance {},
	marcador: class extends self.ISpriteInstance {},
	colisão: class extends self.ISpriteInstance {},
	ElaraF: class extends self.ISpriteInstance {},
	Chão: class extends self.ISpriteInstance {},
	JogarN: class extends self.ISpriteInstance {},
	Texto4: class extends self.ITextInstance {},
	marcador2: class extends self.ISpriteInstance {},
	Parabens: class extends self.ISpriteInstance {},
	planodefundogameover2: class extends self.ITiledBackgroundInstance {},
	Reiniciar2: class extends self.ISpriteInstance {},
	chãoFase1: class extends self.ISpriteInstance {}
}